[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"
description="sqoin training session for rust"
licence="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
